# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту ast1bn@mail.ru если сборка упала
notifications:
  email:
    recipients:
      - ast1bn@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="79976d61-9f73-4279-b21d-5a7e711eae59"